# Generated by Django 3.1 on 2020-11-14 05:12

from django.db import migrations, models
import omnistack11.models


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack11', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='id_for_login',
            field=models.CharField(default=omnistack11.models.get_uuid_8_length, editable=False, max_length=8),
        ),
    ]
