# Generated by Django 3.2 on 2021-04-28 02:25

from django.db import migrations, models
import omnistack11.models


class Migration(migrations.Migration):

    dependencies = [
        ('omnistack11', '0002_ong_id_for_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='id_for_login',
        ),
        migrations.AlterField(
            model_name='ong',
            name='id',
            field=models.CharField(default=omnistack11.models.get_uuid_8_length, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
